[package]
name = "uledger-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5", features = ["std", "simple"] }
askama = { version = "0.14", default-features = false, features = [
    "derive",
    "std",
    "urlencode",
    "config",
] }
axum = { version = "0.8", default-features = false, features = [
    "tracing",
    "macros",
    "http1",
    "http2",
    "json",
    "tokio",
    "form",
    "query",
] }
axum-extra = { version = "0.10", features = ["cookie", "cookie-private"] }
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
figment = { version = "0.10", features = ["env"] }
hex = "0.4"
lettre = { version = "0.11", default-features = false, features = [
    "tracing",
    "tokio1",
    "tokio1-native-tls",
    "serde",
    "builder",
    "smtp-transport",
] }
rand = "0.9"
regex = "1.11"
reqwest = { version = "0.12", default-features = false, features = [
    "http2",
    "charset",
    "gzip",
    "json",
    "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5"
serde_json = "1.0"
sqlx = { version = "0.8", features = [
    "migrate",
    "macros",
    "runtime-tokio",
    "postgres",
    "uuid",
    "chrono",
    "derive",
] }
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1.47", default-features = false, features = [
    "rt-multi-thread",
] }
tower-http = { version = "0.6", features = [
    "set-header",
    "compression-br",
    "compression-gzip",
    "compression-zstd",
    "decompression-br",
    "decompression-gzip",
    "decompression-zstd",
    "validate-request",
] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.18", features = ["serde", "v4", "v7"] }
dotenvy = "0.15"
askama_web = { version = "0.14", default-features = false, features = [
    "tracing-0.1",
    "axum-core-0.5",
] }
grass = { git = "https://github.com/connorskees/grass", rev = "refs/pull/103/head" }
mime = "0.3"
tower-sessions = { version = "0.14", default-features = false, features = [
    "axum-core",
    "signed",
] }
tower-sessions-redis-store = "0.16"
