[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "*"
anyhow = "*"

tokio = { version = "*", features = ["full"] }
tracing = "*"
tracing-subscriber = "*"

figment = { version = "*", features = ["env"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"

chrono = { version = "*", features = ["serde"] }
uuid = { version = "*", features = ["serde", "v4", "v7"] }
sqlx = { version = "*", features = [
    "migrate",
    "macros",
    "runtime-tokio",
    "postgres",
    "uuid",
    "chrono",
] }

axum = { version = "*", features = ["tracing"] }
tower-http = { version = "*", features = [
    "set-header",
    "compression-br",
    "compression-gzip",
    "compression-zstd",
    "decompression-br",
    "decompression-gzip",
    "decompression-zstd",
] }
