[package]
name = "uledger-frontend-web"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { version = "0.14", default-features = false, features = [
    "derive",
    "std",
    "urlencode",
    "config",
] }
askama_web = { version = "0.14", default-features = false, features = [
    "tracing-0.1",
    "axum-core-0.5",
] }
grass = { git = "https://github.com/connorskees/grass", rev = "refs/pull/103/head" }
