[package]
name = "lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"] }
strum = { version = "*", features = ["derive"] }
sqlx = { version = "*", features = ["derive"] }
rand = { version = "*", features = ["getrandom"] }
chrono = "*"
uuid = "*"
hex = "*"
